apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: ingress-nginx
spec:
  selector:
    app: sample-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: flyingsmurf/sample-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

